import type { SpeciesKey } from "./ingredients";

export type Requirement = {
  name: string;
  species: SpeciesKey;

  energy: number;
  energyMax?: number;

  protein: number;
  proteinMax?: number;

  lysine: number;
  lysineMax?: number;

  methionine: number;
  methionineMax?: number;

  metCys: number;
  metCysMax?: number;

  threonine: number;
  threonineMax?: number;

  tryptophan: number;
  tryptophanMax?: number;

  arginine: number;
  arginineMax?: number;

  glycineSerine: number;
  glycineSerineMax?: number;

  histidine: number;
  histidineMax?: number;

  isoleucine: number;
  isoleucineMax?: number;

  leucine: number;
  leucineMax?: number;

  phenylalanine: number;
  phenylalanineMax?: number;

  tyrosine: number;
  tyrosineMax?: number;

  phenylalanineTyrosine: number;
  phenylalanineTyrosineMax?: number;

  valine: number;
  valineMax?: number;

  calcium: number;
  calciumMax?: number;

  availablePhosphorus: number;
  availablePhosphorusMax?: number;

  sodium: number;
  sodiumMax?: number;

  chlorine: number;
  chlorineMax?: number;

  linoleicAcid: number;
  linoleicAcidMax?: number;
};

export const defaultRequirement: Requirement = {
  name: "Ponedora en producción",
  species: "layer",
  energy: 2850,
  energyMax: 3000,
  protein: 16,
  proteinMax: 18.5,
  lysine: 0.87,
  lysineMax: 1.1,
  methionine: 0.43,
  methionineMax: 0.55,
  metCys: 0.82,
  metCysMax: 1,
  threonine: 0.65,
  threonineMax: 0.85,
  tryptophan: 0.21,
  tryptophanMax: 0.3,
  arginine: 0.88,
  arginineMax: 1.2,
  glycineSerine: 0,
  glycineSerineMax: 0,
  histidine: 0.25,
  histidineMax: 0.45,
  isoleucine: 0.7,
  isoleucineMax: 0.95,
  leucine: 1.1,
  leucineMax: 1.8,
  phenylalanine: 0.65,
  phenylalanineMax: 1,
  tyrosine: 0.45,
  tyrosineMax: 0.8,
  phenylalanineTyrosine: 1.1,
  phenylalanineTyrosineMax: 1.7,
  valine: 0.79,
  valineMax: 1.05,
  calcium: 3.7,
  calciumMax: 4.2,
  availablePhosphorus: 0.38,
  availablePhosphorusMax: 0.5,
  sodium: 0.16,
  sodiumMax: 0.23,
  chlorine: 0.16,
  chlorineMax: 0.25,
  linoleicAcid: 1.8,
  linoleicAcidMax: 2.5
};

function withDefaults(profile: Partial<Requirement> & { name: string }): Requirement {
  return {
    ...defaultRequirement,
    ...profile,
    species: profile.species || defaultRequirement.species
  };
}

export const baseRequirementProfiles: Requirement[] = [
  withDefaults({
    name: "Ponedora producción",
    species: "layer"
  }),
  withDefaults({
    name: "Ponedora producción dig",
    species: "layerDig"
  }),
  withDefaults({
    name: "Ponedora verano",
    species: "layer",
    energy: 3150,
    energyMax: 3250,
    protein: 16.5,
    sodium: 0.2,
    sodiumMax: 0.25,
    calcium: 3.64,
    availablePhosphorus: 0.39,
    linoleicAcid: 1.9,
    linoleicAcidMax: 2.6
  }),
  withDefaults({
    name: "Cobb 500 inicio",
    species: "broiler",
    energy: 3000,
    energyMax: 3100,
    protein: 22,
    proteinMax: 24,
    lysine: 1.28,
    lysineMax: 1.5,
    methionine: 0.5,
    methionineMax: 0.65,
    metCys: 0.95,
    metCysMax: 1.15,
    threonine: 0.86,
    threonineMax: 1.05,
    tryptophan: 0.23,
    tryptophanMax: 0.32,
    arginine: 1.35,
    arginineMax: 1.65,
    glycineSerine: 1.55,
    glycineSerineMax: 2.3,
    histidine: 0.42,
    histidineMax: 0.65,
    isoleucine: 0.85,
    isoleucineMax: 1.05,
    leucine: 1.4,
    leucineMax: 2.3,
    phenylalanine: 0.75,
    phenylalanineMax: 1.2,
    tyrosine: 0.6,
    tyrosineMax: 1,
    phenylalanineTyrosine: 1.35,
    phenylalanineTyrosineMax: 2,
    valine: 0.95,
    valineMax: 1.15,
    calcium: 0.95,
    calciumMax: 1.1,
    availablePhosphorus: 0.48,
    availablePhosphorusMax: 0.6,
    sodium: 0.2,
    sodiumMax: 0.25,
    chlorine: 0.2,
    chlorineMax: 0.28,
    linoleicAcid: 1.2,
    linoleicAcidMax: 2.5
  }),
  withDefaults({
    name: "Cobb 500 inicio dig",
    species: "broilerDig",
    energy: 3000,
    energyMax: 3100,
    protein: 22,
    proteinMax: 24,
    lysine: 1.28,
    lysineMax: 1.5,
    methionine: 0.5,
    methionineMax: 0.65,
    metCys: 0.95,
    metCysMax: 1.15,
    threonine: 0.86,
    threonineMax: 1.05,
    tryptophan: 0.23,
    tryptophanMax: 0.32,
    arginine: 1.35,
    arginineMax: 1.65,
    glycineSerine: 1.55,
    glycineSerineMax: 2.3,
    histidine: 0.42,
    histidineMax: 0.65,
    isoleucine: 0.85,
    isoleucineMax: 1.05,
    leucine: 1.4,
    leucineMax: 2.3,
    phenylalanine: 0.75,
    phenylalanineMax: 1.2,
    tyrosine: 0.6,
    tyrosineMax: 1,
    phenylalanineTyrosine: 1.35,
    phenylalanineTyrosineMax: 2,
    valine: 0.95,
    valineMax: 1.15,
    calcium: 0.95,
    calciumMax: 1.1,
    availablePhosphorus: 0.48,
    availablePhosphorusMax: 0.6,
    sodium: 0.2,
    sodiumMax: 0.25,
    chlorine: 0.2,
    chlorineMax: 0.28,
    linoleicAcid: 1.2,
    linoleicAcidMax: 2.5
  }),
  withDefaults({
    name: "Cobb 500 inicio SE",
    species: "broilerSE",
    energy: 3000,
    energyMax: 3100,
    protein: 22,
    proteinMax: 24,
    lysine: 1.28,
    lysineMax: 1.5,
    methionine: 0.5,
    methionineMax: 0.65,
    metCys: 0.95,
    metCysMax: 1.15,
    threonine: 0.86,
    threonineMax: 1.05,
    tryptophan: 0.23,
    tryptophanMax: 0.32,
    arginine: 1.35,
    arginineMax: 1.65,
    glycineSerine: 1.55,
    glycineSerineMax: 2.3,
    histidine: 0.42,
    histidineMax: 0.65,
    isoleucine: 0.85,
    isoleucineMax: 1.05,
    leucine: 1.4,
    leucineMax: 2.3,
    phenylalanine: 0.75,
    phenylalanineMax: 1.2,
    tyrosine: 0.6,
    tyrosineMax: 1,
    phenylalanineTyrosine: 1.35,
    phenylalanineTyrosineMax: 2,
    valine: 0.95,
    valineMax: 1.15,
    calcium: 0.95,
    calciumMax: 1.1,
    availablePhosphorus: 0.48,
    availablePhosphorusMax: 0.6,
    sodium: 0.2,
    sodiumMax: 0.25,
    chlorine: 0.2,
    chlorineMax: 0.28,
    linoleicAcid: 1.2,
    linoleicAcidMax: 2.5
  }),
  withDefaults({
    name: "Cobb 500 crecimiento",
    species: "broiler",
    energy: 3100,
    energyMax: 3200,
    protein: 20,
    proteinMax: 22,
    lysine: 1.15,
    lysineMax: 1.35,
    methionine: 0.47,
    methionineMax: 0.6,
    metCys: 0.88,
    metCysMax: 1.08,
    threonine: 0.77,
    threonineMax: 0.95,
    tryptophan: 0.2,
    tryptophanMax: 0.3,
    arginine: 1.22,
    arginineMax: 1.5,
    glycineSerine: 1.4,
    glycineSerineMax: 2.1,
    histidine: 0.38,
    histidineMax: 0.6,
    isoleucine: 0.78,
    isoleucineMax: 1,
    leucine: 1.28,
    leucineMax: 2.15,
    phenylalanine: 0.7,
    phenylalanineMax: 1.15,
    tyrosine: 0.55,
    tyrosineMax: 0.95,
    phenylalanineTyrosine: 1.25,
    phenylalanineTyrosineMax: 1.9,
    valine: 0.86,
    valineMax: 1.1,
    calcium: 0.85,
    calciumMax: 1,
    availablePhosphorus: 0.42,
    availablePhosphorusMax: 0.55,
    sodium: 0.19,
    sodiumMax: 0.25,
    chlorine: 0.19,
    chlorineMax: 0.28,
    linoleicAcid: 1.1,
    linoleicAcidMax: 2.5
  }),
  withDefaults({
    name: "Cobb 500 crecimiento dig",
    species: "broilerDig",
    energy: 3100,
    energyMax: 3200,
    protein: 20,
    proteinMax: 22,
    lysine: 1.15,
    lysineMax: 1.35,
    methionine: 0.47,
    methionineMax: 0.6,
    metCys: 0.88,
    metCysMax: 1.08,
    threonine: 0.77,
    threonineMax: 0.95,
    tryptophan: 0.2,
    tryptophanMax: 0.3,
    arginine: 1.22,
    arginineMax: 1.5,
    glycineSerine: 1.4,
    glycineSerineMax: 2.1,
    histidine: 0.38,
    histidineMax: 0.6,
    isoleucine: 0.78,
    isoleucineMax: 1,
    leucine: 1.28,
    leucineMax: 2.15,
    phenylalanine: 0.7,
    phenylalanineMax: 1.15,
    tyrosine: 0.55,
    tyrosineMax: 0.95,
    phenylalanineTyrosine: 1.25,
    phenylalanineTyrosineMax: 1.9,
    valine: 0.86,
    valineMax: 1.1,
    calcium: 0.85,
    calciumMax: 1,
    availablePhosphorus: 0.42,
    availablePhosphorusMax: 0.55,
    sodium: 0.19,
    sodiumMax: 0.25,
    chlorine: 0.19,
    chlorineMax: 0.28,
    linoleicAcid: 1.1,
    linoleicAcidMax: 2.5
  }),
  withDefaults({
    name: "Cobb 500 crecimiento SE",
    species: "broilerSE",
    energy: 3100,
    energyMax: 3200,
    protein: 20,
    proteinMax: 22,
    lysine: 1.15,
    lysineMax: 1.35,
    methionine: 0.47,
    methionineMax: 0.6,
    metCys: 0.88,
    metCysMax: 1.08,
    threonine: 0.77,
    threonineMax: 0.95,
    tryptophan: 0.2,
    tryptophanMax: 0.3,
    arginine: 1.22,
    arginineMax: 1.5,
    glycineSerine: 1.4,
    glycineSerineMax: 2.1,
    histidine: 0.38,
    histidineMax: 0.6,
    isoleucine: 0.78,
    isoleucineMax: 1,
    leucine: 1.28,
    leucineMax: 2.15,
    phenylalanine: 0.7,
    phenylalanineMax: 1.15,
    tyrosine: 0.55,
    tyrosineMax: 0.95,
    phenylalanineTyrosine: 1.25,
    phenylalanineTyrosineMax: 1.9,
    valine: 0.86,
    valineMax: 1.1,
    calcium: 0.85,
    calciumMax: 1,
    availablePhosphorus: 0.42,
    availablePhosphorusMax: 0.55,
    sodium: 0.19,
    sodiumMax: 0.25,
    chlorine: 0.19,
    chlorineMax: 0.28,
    linoleicAcid: 1.1,
    linoleicAcidMax: 2.5
  }),
  withDefaults({
    name: "Cobb 500 engorde",
    species: "broiler",
    energy: 3200,
    energyMax: 3300,
    protein: 18.5,
    proteinMax: 20.5,
    lysine: 1.05,
    lysineMax: 1.25,
    methionine: 0.43,
    methionineMax: 0.55,
    metCys: 0.82,
    metCysMax: 1,
    threonine: 0.7,
    threonineMax: 0.9,
    tryptophan: 0.18,
    tryptophanMax: 0.28,
    arginine: 1.1,
    arginineMax: 1.4,
    glycineSerine: 1.25,
    glycineSerineMax: 2,
    histidine: 0.34,
    histidineMax: 0.55,
    isoleucine: 0.72,
    isoleucineMax: 0.95,
    leucine: 1.18,
    leucineMax: 2,
    phenylalanine: 0.65,
    phenylalanineMax: 1.1,
    tyrosine: 0.5,
    tyrosineMax: 0.9,
    phenylalanineTyrosine: 1.15,
    phenylalanineTyrosineMax: 1.8,
    valine: 0.8,
    valineMax: 1,
    calcium: 0.78,
    calciumMax: 0.95,
    availablePhosphorus: 0.38,
    availablePhosphorusMax: 0.5,
    sodium: 0.18,
    sodiumMax: 0.24,
    chlorine: 0.18,
    chlorineMax: 0.26,
    linoleicAcid: 1,
    linoleicAcidMax: 2.3
  }),
  withDefaults({
    name: "Cobb 500 engorde dig",
    species: "broilerDig",
    energy: 3200,
    energyMax: 3300,
    protein: 18.5,
    proteinMax: 20.5,
    lysine: 1.05,
    lysineMax: 1.25,
    methionine: 0.43,
    methionineMax: 0.55,
    metCys: 0.82,
    metCysMax: 1,
    threonine: 0.7,
    threonineMax: 0.9,
    tryptophan: 0.18,
    tryptophanMax: 0.28,
    arginine: 1.1,
    arginineMax: 1.4,
    glycineSerine: 1.25,
    glycineSerineMax: 2,
    histidine: 0.34,
    histidineMax: 0.55,
    isoleucine: 0.72,
    isoleucineMax: 0.95,
    leucine: 1.18,
    leucineMax: 2,
    phenylalanine: 0.65,
    phenylalanineMax: 1.1,
    tyrosine: 0.5,
    tyrosineMax: 0.9,
    phenylalanineTyrosine: 1.15,
    phenylalanineTyrosineMax: 1.8,
    valine: 0.8,
    valineMax: 1,
    calcium: 0.78,
    calciumMax: 0.95,
    availablePhosphorus: 0.38,
    availablePhosphorusMax: 0.5,
    sodium: 0.18,
    sodiumMax: 0.24,
    chlorine: 0.18,
    chlorineMax: 0.26,
    linoleicAcid: 1,
    linoleicAcidMax: 2.3
  }),
  withDefaults({
    name: "Cobb 500 engorde SE",
    species: "broilerSE",
    energy: 3200,
    energyMax: 3300,
    protein: 18.5,
    proteinMax: 20.5,
    lysine: 1.05,
    lysineMax: 1.25,
    methionine: 0.43,
    methionineMax: 0.55,
    metCys: 0.82,
    metCysMax: 1,
    threonine: 0.7,
    threonineMax: 0.9,
    tryptophan: 0.18,
    tryptophanMax: 0.28,
    arginine: 1.1,
    arginineMax: 1.4,
    glycineSerine: 1.25,
    glycineSerineMax: 2,
    histidine: 0.34,
    histidineMax: 0.55,
    isoleucine: 0.72,
    isoleucineMax: 0.95,
    leucine: 1.18,
    leucineMax: 2,
    phenylalanine: 0.65,
    phenylalanineMax: 1.1,
    tyrosine: 0.5,
    tyrosineMax: 0.9,
    phenylalanineTyrosine: 1.15,
    phenylalanineTyrosineMax: 1.8,
    valine: 0.8,
    valineMax: 1,
    calcium: 0.78,
    calciumMax: 0.95,
    availablePhosphorus: 0.38,
    availablePhosphorusMax: 0.5,
    sodium: 0.18,
    sodiumMax: 0.24,
    chlorine: 0.18,
    chlorineMax: 0.26,
    linoleicAcid: 1,
    linoleicAcidMax: 2.3
  }),
  withDefaults({
    name: "Cerdo crecimiento",
    species: "pig",
    energy: 3250,
    energyMax: 3400,
    protein: 18,
    proteinMax: 20,
    lysine: 1.05,
    lysineMax: 1.3,
    methionine: 0.32,
    methionineMax: 0.5,
    metCys: 0.6,
    metCysMax: 0.8,
    threonine: 0.68,
    threonineMax: 0.9,
    tryptophan: 0.19,
    tryptophanMax: 0.28,
    arginine: 0.75,
    arginineMax: 1.2,
    glycineSerine: 0,
    glycineSerineMax: 0,
    histidine: 0.36,
    histidineMax: 0.6,
    isoleucine: 0.6,
    isoleucineMax: 0.85,
    leucine: 1.05,
    leucineMax: 1.8,
    phenylalanine: 0.6,
    phenylalanineMax: 1,
    tyrosine: 0.45,
    tyrosineMax: 0.85,
    phenylalanineTyrosine: 1.05,
    phenylalanineTyrosineMax: 1.6,
    valine: 0.7,
    valineMax: 0.95,
    calcium: 0.75,
    calciumMax: 0.95,
    availablePhosphorus: 0.35,
    availablePhosphorusMax: 0.5,
    sodium: 0.18,
    sodiumMax: 0.25,
    chlorine: 0.18,
    chlorineMax: 0.28,
    linoleicAcid: 1,
    linoleicAcidMax: 2.5
  }),
  withDefaults({
    name: "Cerdo crecimiento dig",
    species: "pigDig",
    energy: 3250,
    energyMax: 3400,
    protein: 18,
    proteinMax: 20,
    lysine: 1.05,
    lysineMax: 1.3,
    methionine: 0.32,
    methionineMax: 0.5,
    metCys: 0.6,
    metCysMax: 0.8,
    threonine: 0.68,
    threonineMax: 0.9,
    tryptophan: 0.19,
    tryptophanMax: 0.28,
    arginine: 0.75,
    arginineMax: 1.2,
    glycineSerine: 0,
    glycineSerineMax: 0,
    histidine: 0.36,
    histidineMax: 0.6,
    isoleucine: 0.6,
    isoleucineMax: 0.85,
    leucine: 1.05,
    leucineMax: 1.8,
    phenylalanine: 0.6,
    phenylalanineMax: 1,
    tyrosine: 0.45,
    tyrosineMax: 0.85,
    phenylalanineTyrosine: 1.05,
    phenylalanineTyrosineMax: 1.6,
    valine: 0.7,
    valineMax: 0.95,
    calcium: 0.75,
    calciumMax: 0.95,
    availablePhosphorus: 0.35,
    availablePhosphorusMax: 0.5,
    sodium: 0.18,
    sodiumMax: 0.25,
    chlorine: 0.18,
    chlorineMax: 0.28,
    linoleicAcid: 1,
    linoleicAcidMax: 2.5
  }),
  withDefaults({
    name: "Cerdo crecimiento SE",
    species: "pigSE",
    energy: 3250,
    energyMax: 3400,
    protein: 18,
    proteinMax: 20,
    lysine: 1.05,
    lysineMax: 1.3,
    methionine: 0.32,
    methionineMax: 0.5,
    metCys: 0.6,
    metCysMax: 0.8,
    threonine: 0.68,
    threonineMax: 0.9,
    tryptophan: 0.19,
    tryptophanMax: 0.28,
    arginine: 0.75,
    arginineMax: 1.2,
    glycineSerine: 0,
    glycineSerineMax: 0,
    histidine: 0.36,
    histidineMax: 0.6,
    isoleucine: 0.6,
    isoleucineMax: 0.85,
    leucine: 1.05,
    leucineMax: 1.8,
    phenylalanine: 0.6,
    phenylalanineMax: 1,
    tyrosine: 0.45,
    tyrosineMax: 0.85,
    phenylalanineTyrosine: 1.05,
    phenylalanineTyrosineMax: 1.6,
    valine: 0.7,
    valineMax: 0.95,
    calcium: 0.75,
    calciumMax: 0.95,
    availablePhosphorus: 0.35,
    availablePhosphorusMax: 0.5,
    sodium: 0.18,
    sodiumMax: 0.25,
    chlorine: 0.18,
    chlorineMax: 0.28,
    linoleicAcid: 1,
    linoleicAcidMax: 2.5
  }),
  withDefaults({
    name: "Cerdo engorde",
    species: "pig",
    energy: 3250,
    energyMax: 3400,
    protein: 16,
    proteinMax: 18.5,
    lysine: 0.85,
    lysineMax: 1.1,
    methionine: 0.27,
    methionineMax: 0.45,
    metCys: 0.52,
    metCysMax: 0.75,
    threonine: 0.55,
    threonineMax: 0.8,
    tryptophan: 0.16,
    tryptophanMax: 0.25,
    arginine: 0.65,
    arginineMax: 1.1,
    glycineSerine: 0,
    glycineSerineMax: 0,
    histidine: 0.3,
    histidineMax: 0.55,
    isoleucine: 0.5,
    isoleucineMax: 0.75,
    leucine: 0.9,
    leucineMax: 1.6,
    phenylalanine: 0.5,
    phenylalanineMax: 0.9,
    tyrosine: 0.38,
    tyrosineMax: 0.75,
    phenylalanineTyrosine: 0.88,
    phenylalanineTyrosineMax: 1.45,
    valine: 0.6,
    valineMax: 0.85,
    calcium: 0.65,
    calciumMax: 0.85,
    availablePhosphorus: 0.3,
    availablePhosphorusMax: 0.45,
    sodium: 0.16,
    sodiumMax: 0.24,
    chlorine: 0.16,
    chlorineMax: 0.26,
    linoleicAcid: 0.8,
    linoleicAcidMax: 2.3
  }),
  withDefaults({
    name: "Cerdo engorde dig",
    species: "pigDig",
    energy: 3250,
    energyMax: 3400,
    protein: 16,
    proteinMax: 18.5,
    lysine: 0.85,
    lysineMax: 1.1,
    methionine: 0.27,
    methionineMax: 0.45,
    metCys: 0.52,
    metCysMax: 0.75,
    threonine: 0.55,
    threonineMax: 0.8,
    tryptophan: 0.16,
    tryptophanMax: 0.25,
    arginine: 0.65,
    arginineMax: 1.1,
    glycineSerine: 0,
    glycineSerineMax: 0,
    histidine: 0.3,
    histidineMax: 0.55,
    isoleucine: 0.5,
    isoleucineMax: 0.75,
    leucine: 0.9,
    leucineMax: 1.6,
    phenylalanine: 0.5,
    phenylalanineMax: 0.9,
    tyrosine: 0.38,
    tyrosineMax: 0.75,
    phenylalanineTyrosine: 0.88,
    phenylalanineTyrosineMax: 1.45,
    valine: 0.6,
    valineMax: 0.85,
    calcium: 0.65,
    calciumMax: 0.85,
    availablePhosphorus: 0.3,
    availablePhosphorusMax: 0.45,
    sodium: 0.16,
    sodiumMax: 0.24,
    chlorine: 0.16,
    chlorineMax: 0.26,
    linoleicAcid: 0.8,
    linoleicAcidMax: 2.3
  }),
  withDefaults({
    name: "Cerdo engorde SE",
    species: "pigSE",
    energy: 3250,
    energyMax: 3400,
    protein: 16,
    proteinMax: 18.5,
    lysine: 0.85,
    lysineMax: 1.1,
    methionine: 0.27,
    methionineMax: 0.45,
    metCys: 0.52,
    metCysMax: 0.75,
    threonine: 0.55,
    threonineMax: 0.8,
    tryptophan: 0.16,
    tryptophanMax: 0.25,
    arginine: 0.65,
    arginineMax: 1.1,
    glycineSerine: 0,
    glycineSerineMax: 0,
    histidine: 0.3,
    histidineMax: 0.55,
    isoleucine: 0.5,
    isoleucineMax: 0.75,
    leucine: 0.9,
    leucineMax: 1.6,
    phenylalanine: 0.5,
    phenylalanineMax: 0.9,
    tyrosine: 0.38,
    tyrosineMax: 0.75,
    phenylalanineTyrosine: 0.88,
    phenylalanineTyrosineMax: 1.45,
    valine: 0.6,
    valineMax: 0.85,
    calcium: 0.65,
    calciumMax: 0.85,
    availablePhosphorus: 0.3,
    availablePhosphorusMax: 0.45,
    sodium: 0.16,
    sodiumMax: 0.24,
    chlorine: 0.16,
    chlorineMax: 0.26,
    linoleicAcid: 0.8,
    linoleicAcidMax: 2.3
  }),
  withDefaults({
    name: "Cuy engorde",
    species: "guineaPig",
    energy: 2800,
    energyMax: 3000,
    protein: 17,
    proteinMax: 19,
    lysine: 0.8,
    lysineMax: 1.1,
    methionine: 0.28,
    methionineMax: 0.45,
    metCys: 0.55,
    metCysMax: 0.8,
    threonine: 0.55,
    threonineMax: 0.8,
    tryptophan: 0.16,
    tryptophanMax: 0.25,
    arginine: 0.8,
    arginineMax: 1.2,
    glycineSerine: 0,
    glycineSerineMax: 0,
    histidine: 0.28,
    histidineMax: 0.5,
    isoleucine: 0.55,
    isoleucineMax: 0.8,
    leucine: 0.95,
    leucineMax: 1.6,
    phenylalanine: 0.55,
    phenylalanineMax: 0.95,
    tyrosine: 0.4,
    tyrosineMax: 0.75,
    phenylalanineTyrosine: 0.95,
    phenylalanineTyrosineMax: 1.5,
    valine: 0.62,
    valineMax: 0.9,
    calcium: 0.8,
    calciumMax: 1.1,
    availablePhosphorus: 0.35,
    availablePhosphorusMax: 0.5,
    sodium: 0.18,
    sodiumMax: 0.25,
    chlorine: 0.18,
    chlorineMax: 0.28,
    linoleicAcid: 0.8,
    linoleicAcidMax: 2.3
  })
];
